<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipment.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.CreateShipmentResponse</code>
 */
class CreateShipmentResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string reqId = 1;</code>
     */
    protected $reqId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $reqId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Shipment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string reqId = 1;</code>
     * @return string
     */
    public function getReqId()
    {
        return $this->reqId;
    }

    /**
     * Generated from protobuf field <code>string reqId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setReqId($var)
    {
        GPBUtil::checkString($var, True);
        $this->reqId = $var;

        return $this;
    }

}

