<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipment.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.CreateShipmentRequest</code>
 */
class CreateShipmentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string orderNumber = 1;</code>
     */
    protected $orderNumber = '';
    /**
     * Generated from protobuf field <code>string carrierCode = 2;</code>
     */
    protected $carrierCode = '';
    /**
     * Generated from protobuf field <code>string serviceLevel = 3;</code>
     */
    protected $serviceLevel = '';
    /**
     * Generated from protobuf field <code>string trackingNumber = 4;</code>
     */
    protected $trackingNumber = '';
    /**
     * Generated from protobuf field <code>string shippingDate = 5;</code>
     */
    protected $shippingDate = '';
    /**
     * Generated from protobuf field <code>repeated .pb.ShipmentItem items = 6;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $orderNumber
     *     @type string $carrierCode
     *     @type string $serviceLevel
     *     @type string $trackingNumber
     *     @type string $shippingDate
     *     @type \Pb\ShipmentItem[]|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Shipment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string orderNumber = 1;</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->orderNumber;
    }

    /**
     * Generated from protobuf field <code>string orderNumber = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string carrierCode = 2;</code>
     * @return string
     */
    public function getCarrierCode()
    {
        return $this->carrierCode;
    }

    /**
     * Generated from protobuf field <code>string carrierCode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCarrierCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->carrierCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string serviceLevel = 3;</code>
     * @return string
     */
    public function getServiceLevel()
    {
        return $this->serviceLevel;
    }

    /**
     * Generated from protobuf field <code>string serviceLevel = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->serviceLevel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trackingNumber = 4;</code>
     * @return string
     */
    public function getTrackingNumber()
    {
        return $this->trackingNumber;
    }

    /**
     * Generated from protobuf field <code>string trackingNumber = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackingNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->trackingNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shippingDate = 5;</code>
     * @return string
     */
    public function getShippingDate()
    {
        return $this->shippingDate;
    }

    /**
     * Generated from protobuf field <code>string shippingDate = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->shippingDate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.ShipmentItem items = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.ShipmentItem items = 6;</code>
     * @param \Pb\ShipmentItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\ShipmentItem::class);
        $this->items = $arr;

        return $this;
    }

}

