<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.Order</code>
 */
class Order extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string orderId = 1;</code>
     */
    protected $orderId = '';
    /**
     * Generated from protobuf field <code>.pb.User user = 2;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>.pb.Shipping shipping = 3;</code>
     */
    protected $shipping = null;
    /**
     * Generated from protobuf field <code>string orderNumber = 4;</code>
     */
    protected $orderNumber = '';
    /**
     * Generated from protobuf field <code>string shopId = 5;</code>
     */
    protected $shopId = '';
    /**
     * Generated from protobuf field <code>string orderTime = 6;</code>
     */
    protected $orderTime = '';
    /**
     * Generated from protobuf field <code>string orderStatus = 7;</code>
     */
    protected $orderStatus = '';
    /**
     * Generated from protobuf field <code>double orderAmount = 8;</code>
     */
    protected $orderAmount = 0.0;
    /**
     * Generated from protobuf field <code>repeated .pb.Item products = 9;</code>
     */
    private $products;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $orderId
     *     @type \Pb\User $user
     *     @type \Pb\Shipping $shipping
     *     @type string $orderNumber
     *     @type string $shopId
     *     @type string $orderTime
     *     @type string $orderStatus
     *     @type float $orderAmount
     *     @type \Pb\Item[]|\Google\Protobuf\Internal\RepeatedField $products
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string orderId = 1;</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * Generated from protobuf field <code>string orderId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.User user = 2;</code>
     * @return \Pb\User
     */
    public function getUser()
    {
        return isset($this->user) ? $this->user : null;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.pb.User user = 2;</code>
     * @param \Pb\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Pb\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.Shipping shipping = 3;</code>
     * @return \Pb\Shipping
     */
    public function getShipping()
    {
        return isset($this->shipping) ? $this->shipping : null;
    }

    public function hasShipping()
    {
        return isset($this->shipping);
    }

    public function clearShipping()
    {
        unset($this->shipping);
    }

    /**
     * Generated from protobuf field <code>.pb.Shipping shipping = 3;</code>
     * @param \Pb\Shipping $var
     * @return $this
     */
    public function setShipping($var)
    {
        GPBUtil::checkMessage($var, \Pb\Shipping::class);
        $this->shipping = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string orderNumber = 4;</code>
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->orderNumber;
    }

    /**
     * Generated from protobuf field <code>string orderNumber = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shopId = 5;</code>
     * @return string
     */
    public function getShopId()
    {
        return $this->shopId;
    }

    /**
     * Generated from protobuf field <code>string shopId = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setShopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shopId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string orderTime = 6;</code>
     * @return string
     */
    public function getOrderTime()
    {
        return $this->orderTime;
    }

    /**
     * Generated from protobuf field <code>string orderTime = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string orderStatus = 7;</code>
     * @return string
     */
    public function getOrderStatus()
    {
        return $this->orderStatus;
    }

    /**
     * Generated from protobuf field <code>string orderStatus = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double orderAmount = 8;</code>
     * @return float
     */
    public function getOrderAmount()
    {
        return $this->orderAmount;
    }

    /**
     * Generated from protobuf field <code>double orderAmount = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setOrderAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->orderAmount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Item products = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Item products = 9;</code>
     * @param \Pb\Item[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProducts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\Item::class);
        $this->products = $arr;

        return $this;
    }

}

