<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.Shipping</code>
 */
class Shipping extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string shippingName = 1;</code>
     */
    protected $shippingName = '';
    /**
     * Generated from protobuf field <code>string shippingTelephone = 2;</code>
     */
    protected $shippingTelephone = '';
    /**
     * Generated from protobuf field <code>string shippingEmail = 3;</code>
     */
    protected $shippingEmail = '';
    /**
     * Generated from protobuf field <code>string carrierCode = 4;</code>
     */
    protected $carrierCode = '';
    /**
     * Generated from protobuf field <code>string serviceLevel = 5;</code>
     */
    protected $serviceLevel = '';
    /**
     * Generated from protobuf field <code>string shipChannel = 6;</code>
     */
    protected $shipChannel = '';
    /**
     * Generated from protobuf field <code>string shippingPostcode = 7;</code>
     */
    protected $shippingPostcode = '';
    /**
     * Generated from protobuf field <code>string shippingCountry = 8;</code>
     */
    protected $shippingCountry = '';
    /**
     * Generated from protobuf field <code>string shippingState = 9;</code>
     */
    protected $shippingState = '';
    /**
     * Generated from protobuf field <code>string shippingCity = 10;</code>
     */
    protected $shippingCity = '';
    /**
     * Generated from protobuf field <code>string shippingAddress1 = 11;</code>
     */
    protected $shippingAddress1 = '';
    /**
     * Generated from protobuf field <code>string shippingAddress2 = 12;</code>
     */
    protected $shippingAddress2 = '';
    /**
     * Generated from protobuf field <code>string shippingAddress3 = 13;</code>
     */
    protected $shippingAddress3 = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $shippingName
     *     @type string $shippingTelephone
     *     @type string $shippingEmail
     *     @type string $carrierCode
     *     @type string $serviceLevel
     *     @type string $shipChannel
     *     @type string $shippingPostcode
     *     @type string $shippingCountry
     *     @type string $shippingState
     *     @type string $shippingCity
     *     @type string $shippingAddress1
     *     @type string $shippingAddress2
     *     @type string $shippingAddress3
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string shippingName = 1;</code>
     * @return string
     */
    public function getShippingName()
    {
        return $this->shippingName;
    }

    /**
     * Generated from protobuf field <code>string shippingName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingName($var)
    {
        GPBUtil::checkString($var, True);
        $this->shippingName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shippingTelephone = 2;</code>
     * @return string
     */
    public function getShippingTelephone()
    {
        return $this->shippingTelephone;
    }

    /**
     * Generated from protobuf field <code>string shippingTelephone = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingTelephone($var)
    {
        GPBUtil::checkString($var, True);
        $this->shippingTelephone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shippingEmail = 3;</code>
     * @return string
     */
    public function getShippingEmail()
    {
        return $this->shippingEmail;
    }

    /**
     * Generated from protobuf field <code>string shippingEmail = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->shippingEmail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string carrierCode = 4;</code>
     * @return string
     */
    public function getCarrierCode()
    {
        return $this->carrierCode;
    }

    /**
     * Generated from protobuf field <code>string carrierCode = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCarrierCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->carrierCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string serviceLevel = 5;</code>
     * @return string
     */
    public function getServiceLevel()
    {
        return $this->serviceLevel;
    }

    /**
     * Generated from protobuf field <code>string serviceLevel = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->serviceLevel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shipChannel = 6;</code>
     * @return string
     */
    public function getShipChannel()
    {
        return $this->shipChannel;
    }

    /**
     * Generated from protobuf field <code>string shipChannel = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setShipChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->shipChannel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shippingPostcode = 7;</code>
     * @return string
     */
    public function getShippingPostcode()
    {
        return $this->shippingPostcode;
    }

    /**
     * Generated from protobuf field <code>string shippingPostcode = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingPostcode($var)
    {
        GPBUtil::checkString($var, True);
        $this->shippingPostcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shippingCountry = 8;</code>
     * @return string
     */
    public function getShippingCountry()
    {
        return $this->shippingCountry;
    }

    /**
     * Generated from protobuf field <code>string shippingCountry = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->shippingCountry = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shippingState = 9;</code>
     * @return string
     */
    public function getShippingState()
    {
        return $this->shippingState;
    }

    /**
     * Generated from protobuf field <code>string shippingState = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingState($var)
    {
        GPBUtil::checkString($var, True);
        $this->shippingState = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shippingCity = 10;</code>
     * @return string
     */
    public function getShippingCity()
    {
        return $this->shippingCity;
    }

    /**
     * Generated from protobuf field <code>string shippingCity = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->shippingCity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shippingAddress1 = 11;</code>
     * @return string
     */
    public function getShippingAddress1()
    {
        return $this->shippingAddress1;
    }

    /**
     * Generated from protobuf field <code>string shippingAddress1 = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingAddress1($var)
    {
        GPBUtil::checkString($var, True);
        $this->shippingAddress1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shippingAddress2 = 12;</code>
     * @return string
     */
    public function getShippingAddress2()
    {
        return $this->shippingAddress2;
    }

    /**
     * Generated from protobuf field <code>string shippingAddress2 = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingAddress2($var)
    {
        GPBUtil::checkString($var, True);
        $this->shippingAddress2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shippingAddress3 = 13;</code>
     * @return string
     */
    public function getShippingAddress3()
    {
        return $this->shippingAddress3;
    }

    /**
     * Generated from protobuf field <code>string shippingAddress3 = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingAddress3($var)
    {
        GPBUtil::checkString($var, True);
        $this->shippingAddress3 = $var;

        return $this;
    }

}

